on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
    
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 6007
      VITE_API_URL: http://localhost:6007/api

    steps:
      # Hace checkout del repositorio donde está el workflow
      - name: Checkout repo actual
        uses: actions/checkout@v3

      # Clona el repositorio del proyecto Athena Redux Bank, he creado un fork del proyecto original de ateneaConocimientos para poder ejecutar sin problema si hay un cambio en el repo original
      - name: Clonar repo Athena Redux Bank
        run: |
          git clone https://github.com/javi0420/redux-athena-bank.git app

      # Crea el archivo .env con las variables de entorno necesarias para el backend
      - name: crear archivo .env para backend
        run: |
          echo "MONGO_URI=${{ env.MONGO_URI }}" > app/backend/.env
          echo "JWT_SECRET=${{ env.JWT_SECRET }}" >> app/backend/.env
          echo "PORT=${{ env.PORT }}" >> app/backend/.env
          echo "VITE_API_URL=${{ env.VITE_API_URL }}" >> app/backend/.env
          
      # Instala todas las dependencias necesarias para el backend
      - name: Instalar dependencias de backend
        run: |
          cd app/backend
          npm install

      # Inicia el servidor backend en modo desarrollo y guarda los logs
      - name: Levantar backend
        run: |
          cd app/backend
          npm run dev > backend.log 2>&1 &
        env:
          MONGO_URI: ${{ env.MONGO_URI }}
          JWT_SECRET: ${{ env.JWT_SECRET }}
          PORT: ${{ env.PORT }}
      
      # Instala la herramienta wait-on para poder esperar a que los servicios estén disponibles
      - name: Instalar wait-on
        run: npm install -g wait-on

      # Espera a que el backend esté disponible en el puerto 6007
      - name: Esperar backend
        run: wait-on tcp:6007
      
      # Instala todas las dependencias necesarias para el frontend
      - name: Instalar dependencias de frontend
        run: |
          cd app/frontend
          npm install

      # Inicia el servidor frontend en modo desarrollo y guarda los logs
      - name: Levantar frontend
        run: |
          cd app/frontend
          npm run dev > frontend.log 2>&1 &
        env:
          VITE_API_BASE: ${{ env.VITE_API_BASE }}

      # Espera a que el frontend esté disponible en el puerto 3000
      - name: Esperar frontend
        run: wait-on http://localhost:3000

      # Ejecuta los tests end-to-end con Playwright
      - name: Instalar y ejecutar pruebas e2e con Playwright
        run: |
          cd test
          npx playwright install
          npx playwright test
